### ISSUE TITLE
.rvm/gems/ruby-2.5.3/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- open_api (LoadError)

### ISSUE THREAD

**Issue by hamsa95** [zhandao/zero-rails#5]
while starting the rails server getting .rvm/gems/ruby-2.5.3/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- open_api (LoadError)

**Comment by zhandao** [comment]
This project is under development (on the branch `dev`).
