### ISSUE TITLE
LoadError: cannot load such file -- open_api/generator

### ISSUE THREAD

**Issue by amitdotagarwal** [zhandao/zero-rails#8]
LoadError: cannot load such file -- open_api/generator
/Users/amitagarwal/.rvm/gems/ruby-2.6.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'
/Users/amitagarwal/.rvm/gems/ruby-2.6.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `block in require'
/Users/amitagarwal/.rvm/gems/ruby-2.6.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:256:in `block in load_dependency'
/Users/amitagarwal/.rvm/gems/ruby-2.6.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:662:in `new_constants_in'
/Users/amitagarwal/.rvm/gems/ruby-2.6.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:256:in `load_dependency'
/Users/amitagarwal/.rvm/gems/ruby-2.6.0/gems/activesupport-5.1.6.2/lib/active_support/dependencies.rb:292:in `require'

**Comment by zhandao** [comment]
Not ready to be used, thank you.
