### ISSUE TITLE
NoMethodError: undefined method `cache_url' for nil:NilClass

### ISSUE THREAD

**Issue by amitdotagarwal** [zhandao/zero-rails#9]
NoMethodError: undefined method `cache_url' for nil:NilClass

**Comment by zhandao** [comment]
Not ready to be used.

**Comment by amitdotagarwal** [comment]
I am unable to start this application, could you please guide me how to start this application?

**Comment by zhandao** [comment]
This framework and its readme are still under development.

At present, it has many problems, if you want to use it, I suggest you learn all the gems it used, so you can debug on your own.
